[package]
name = "arch_maintenance"
version = "0.1.0"
authors = ["Paul VEBER <paulveber56@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

cmd_lib = "1.0.13"
sys-info = "0.9.0"